version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: lms/ncg-backend
    ports:
      - "4000:4000"
    environment:
      - PG_DB=trackingdb
      - PG_USER=tracking
      - PG_PASSWORD=
      - PG_HOST=localhost
    restart: always
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trackingdb
      - POSTGRES_USER=tracking
      - POSTGRES_PASSWORD=tracking@204
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}